DavisonCorp/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Threading;
using System.Threading.Tasks;
using System.Web.Mvc;
using DavisonCorpModel.Repository;
using DavisonCorpModel;
using DavisonSocial;


namespace DavisonCorp.Controllers
{
    /// <summary>
    /// Controller for Product{s} and the actions relating to them.
    /// </summary>
    public class ProductController : Controller
    {
        private readonly ProductRepository _myRepository = new ProductRepository(new Davison.Model.Context());

        /// <summary>
        /// Obtains the active product categories as stated in the Davison DB
        /// </summary>
        public ActionResult Index()
        {
            // Attempt to clear session data
            try
            {
                Session.Remove("minPrice");
                Session.Remove("maxPrice");
            }
            catch { Debug.WriteLine("Unable to remove session data for minPrice / maxPrice"); }
            // Returns the active categories from the Davison Model
            return View(_myRepository.GetDavisonCategories());
        }

        /// <summary>
        /// Shows the FilteredByCategory Parent View which shows products from suppliers (as partial views)
        /// </summary>
        /// <param name="categoryName">the name of the category selected</param>
        /// <returns>view of products in the category</returns>
        public ActionResult FilteredByCategory(string categoryName)
        {
            Session["categoryName"] = categoryName; // Store selected category in session data for later actions          
            return View();
        }

        /// <summary>
        /// Obtains Davison Products and displays them in a partial view.
        /// </summary>
        public PartialViewResult DavisonProducts()
        {
            string category = Session["categoryName"].ToString();
            double minPrice = Convert.ToDouble(Session["minPrice"]);
            double maxPrice = Convert.ToDouble(Session["maxPrice"]);
            IEnumerable<StoreProduct> data;
            if((minPrice != 0.0) && (maxPrice != 0.00))
                data = _myRepository.GetDavisonProductsByPrice(category, minPrice, maxPrice);
            else
                data = _myRepository.GetDavisonProducts(category);
            return PartialView("_PartialProducts", data);
        }

        /// <summary>
        /// Obtains UnderCutters Products and displays them in a partial view.
        /// </summary>
        public PartialViewResult UnderCutters()
        {
            string category = Session["categoryName"].ToString();
            double minPrice = Convert.ToDouble(Session["minPrice"]);
            double maxPrice = Convert.ToDouble(Session["maxPrice"]);
            IEnumerable<StoreProduct> data;
            if ((minPrice != 0.0) && (maxPrice != 0.00))
                data = _myRepository.GetUndercuttersProductsByPrice(category, minPrice, maxPrice);
            else
                data = _myRepository.GetUndercuttersProducts(category);
            return PartialView("_PartialProducts", data);
        }

        /// <summary>
        /// Obtains Bazzas Products and displays them in a partial view.
        /// </summary>
        public PartialViewResult BazzasBazaar()
        {
            string category = Session["categoryName"].ToString();
            double minPrice = Convert.ToDouble(Session["minPrice"]);
            double maxPrice = Convert.ToDouble(Session["maxPrice"]);
            IEnumerable<StoreProduct> data;
            if ((minPrice != 0.0) && (maxPrice != 0.00))
                data = _myRepository.GetBazzasProductsByCategoryAndPrice(category, minPrice, maxPrice);
            else
                data = _myRepository.GetBazzasProductsByCategory(category);
            return PartialView("_PartialProducts", data);
        }

        /// <summary>
        /// Obtains DodgyDealers Products and displays them in a partial view.
        /// </summary>
        public PartialViewResult DodgyDealers()
        {
            //create timeout for task - make 4 seconds.
            var tokenSource = new CancellationTokenSource();
            CancellationToken token = tokenSource.Token;
            const int timeOut = 2000;

            string category = Session["categoryName"].ToString();
            double minPrice = Convert.ToDouble(Session["minPrice"]);
            double maxPrice = Convert.ToDouble(Session["maxPrice"]);
            IEnumerable<StoreProduct> data = null;
            if ((minPrice != 0.0) && (maxPrice != 0.00))
            {
                var task = Task.Factory.StartNew(() => _myRepository.GetDodgyDealersProductsByPrice(category, minPrice, maxPrice), token);
                //when timeout is reached stop task or get result.
                if (task.Wait(timeOut, token))
                        data = task.Result;
            }
            else
            {
                var task = Task.Factory.StartNew(() => _myRepository.GetDodgyDealersProducts(category), token);
                if (task.Wait(timeOut, token))
                    data = task.Result;
            }

            return PartialView("_PartialProducts", data);
        }

        /// <summary>
        /// Hit when filtration options have been specified
        /// Updates the root/parent view (FilteredByCategory)
        /// </summary>
        /// <param name="minPrice">minimum product price to display</param>
        /// <param name="maxPrice">maximum product price to display</param>
        /// <returns>Take user back to the FilteredByCategory View</returns>
        public ActionResult UpdateRootView(string minPrice, string maxPrice)
        {
            string category = Session["categoryName"].ToString();
            Session["minPrice"] = minPrice;
            Session["maxPrice"] = maxPrice;
            return RedirectToAction("FilteredByCategory", new { categoryName = category } );
        }

        public ActionResult ProductDetails(string ean)
        {
            ViewBag.eanToShow = ean;
            return View();
        }
    }
}

DavisonCorp/Controllers/ProductDetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DavisonCorp.Controllers
{
    public class ProductDetailsController : Controller
    {
        // GET: ProductDetails
        public ActionResult Index()
        {
            return View();
        }
    }
}

DavisonCorp/Views/Product/FilteredByCategory.cshtml
@{
    ViewBag.Title = "Products";
}

<h3 class="closeToRule">Products</h3>
<hr class="closeRule"/>

@using (Html.BeginForm("UpdateRootView", "Product"))
{
    <p class="myInline">Min Price:</p> @Html.TextBox("minPrice", null, new {@class= "form-control mySelection"});
    <p class="myInline">Max Price:</p> @Html.TextBox("maxPrice", null, new { @class = "form-control mySelection" });
    <button class="btn btn-default" type="submit">Filter</button>
}
<hr class="closeRule"/>

@*<div class="DavisonProducts">
    <h4>> Davison Products</h4>
    <div id="partialContents" class="partialContents" data-url="/Product/DavisonProducts">
        <img src="~/Images/indicator.white.gif" /> Loading Products...
    </div>
</div>

<div class="UnderCutters">
    <h4>> UnderCutters Products</h4>
    <div class="partialContents" data-url="/Product/UnderCutters">
        <img src="~/Images/indicator.white.gif" /> Loading Products...
    </div>
</div>

<div class="BazzasBazaar">
    <h4>> Bazzas Bazaar Products</h4>
    <div class="partialView" data-url="/Product/BazzasBazaar">
        <img src="~/Images/indicator.white.gif" /> Loading Products...
    </div>
</div>


<div class="DodgyDealers">
    <h4>> DodgyDealers Products</h4>
    <div class="partialContents" data-url="/Product/DodgyDealers">
        <img src="~/Images/indicator.white.gif" /> Loading Products... 
    </div>
</div>

<script>
    /// <reference path="../Scripts/jquery-1.8.2-vsdoc.js" />
    var site = site || {};
    site.baseUrl = site.baseUrl || "";
    $(document).ready(function (e) {
        // locate each partial section. If it has a URL set, load the contents into the area.

        // setTimeout(function () { //recently added

        $(".partialContents").each(function (index, item) {
            var url = site.baseUrl + $(item).data("url");
            if (url && url.length > 0) {
                $(item).load(url);
                async: true;
                cache: false;
            }
        });
        $.ajaxSetup({ cache: true, async: true });  //Turn off caching

        // }, 5000); //recently added
    });
</script>*@

<h3>> Davison Products</h3>
@Html.Action("DavisonProducts", "Product")
<h3>> Undercutters Products</h3>
@Html.Action("Undercutters","Product")
<h3>> BazzasBazaar Products</h3>
@Html.Action("BazzasBazaar", "Product")
<h3>> DodgyDealers Products</h3>
@Html.Action("DodgyDealers", "Product")

DavisonCorp/Views/Product/Index.cshtml
@model IEnumerable<Davison.Model.Category>

@{
    ViewBag.Title = "Categories";
}

<h1>Product Categories</h1>
<p>Select a category to be shown the products we have available!</p>

<table class="table">
    @foreach (var item in Model)
    {
        <tr>
            @Html.ActionLink(item.Name, "FilteredByCategory", "Product", new { categoryName = item.Name }, new { @class = "btn" })  
        </tr>
    }
</table>

DavisonCorp/Views/Product/ProductDetails.cshtml
@model IEnumerable<DavisonSocial.Models.ReviewTable>

@{
    ViewBag.Title = "Product Reviews";
}

<h2>ProductDetails</h2>

@{
    try
    {
        foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ProductEan)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ReviewText)
                </td>

            </tr>
        }
    }
    catch
    {
        <tr>Unable to retrieve this product's reviews, please try again later.</tr>
    }
}

DavisonCorp/Views/Product/_PartialProducts.cshtml
@model IEnumerable<DavisonCorpModel.StoreProduct>

<table class="table">
    @{
        try
        {
                 if (!Model.Any())
                 {
                    <p>No items found for this supplier</p>
                 }
            
            foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.ActionLink(item.Name, "ProductDetails", "Product", new { productEan = item.Ean }, new { @class = "btn" })
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    <td>
                        @Html.DisplayFor(model => item.Ean)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ProductSupplier)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.InStock)
                    </td>
                    <td>
                        @Html.DisplayFor(model => item.Price)
                    </td>
                    <td>
                        @using (Html.BeginForm("AddToCart", "Cart"))
                        {

                            @Html.Hidden("productName", item.Name)
                            @Html.Hidden("productPrice", item.Price)
                            @Html.Hidden("productEan", item.Ean)
                            @Html.Hidden("productSupplier", item.ProductSupplier)
                            @Html.Hidden("productCategory", item.CategoryName)
                            @Html.Hidden("compare", "Yes")
                            @Html.Hidden("productId", item.Id)
                            @Html.Hidden("qty",1)
                            <input type="submit" id="myLink" class="btn btn-default buyButton" value="Add To Cart" />
                        }
                    </td>
                    <td>
                        @using (Html.BeginForm("AddToCart", "Cart"))
                        {
                            @Html.Hidden("productName", item.Name)
                            @Html.Hidden("productPrice", item.Price)
                            @Html.Hidden("productEan", item.Ean)
                            @Html.Hidden("productSupplier", item.ProductSupplier)
                            @Html.Hidden("productCategory", item.CategoryName)
                            @Html.Hidden("compare", "No")
                            @Html.Hidden("productId", item.Id)
                            @Html.Hidden("qty", 10)
                            <input type="submit" id="myLink" class="btn btn-default buyButton" value="Add Ten To Cart" />
                        }
                        @{
                            if (item.PriceForTen < (item.Price * 10))
                            {
                                var normalPriceForTen = Math.Round(item.Price * 10,2);
                                var discountPriceForTen = item.PriceForTen;
                                var saving = (normalPriceForTen - discountPriceForTen);
                                string displayString = saving.ToString("0.00");
                                //var savingAmmended = Math.Round(saving, 4);
                                if (saving > 0)
                                {
                                    <p class="smallText">Save @Html.Encode(displayString) when buying!</p>
                                }
                            }
                        }
                    </td>
                </tr>
            }
        }
        catch 
        {
            <tr>Unable to retrieve products from this supplier, please try again later!</tr>
        }
    }
</table>