DavisonCorp/Controllers/RestockerController.cs
using System;
using System.Linq;
using System.Data;
using System.Data.Common;
using System.Collections.Generic;
using System.Diagnostics;
using System.Net.Http;
using System.Web.Mvc;
using DavisonCorpModel.Restocking;

namespace DavisonCorp.Controllers
{
    /// <summary>
    /// Class for controlling restocking
    /// Functionality limited to users within the admin role only.
    /// </summary>
    [Authorize(Roles = "Admin")]
    public class RestockerController : Controller
    {

        /// <summary>
        /// Take user to the ViewDeliverys page
        /// </summary>
        /// <param name="ean">Used to set the ViewBag - which is then passed to later partial views</param>
        /// <returns></returns>
        public ActionResult ViewDeliverys(string ean)
        {
            ViewBag.eanToShow = ean;
            return View();
        }

        // GET: AcceptDelivery
        public ActionResult AcceptDelivery(int deliveryId, string productEan, string restockAmount)
        {
            var client = new HttpClient { BaseAddress = new System.Uri("http://localhost:42636/") };
            client.DefaultRequestHeaders.Accept.ParseAdd("application/json");
            client.Timeout = TimeSpan.FromMilliseconds(20000);
            try
            {
                HttpResponseMessage response =
                    client.GetAsync("AcceptDelivery?deliveryId=" + deliveryId + "&eanNumber=" + productEan +
                                    "&restockQty=" + restockAmount).Result;
                // if successful display the data, otherwise log the bad response
                if (response.IsSuccessStatusCode)
                {
                    IEnumerable<Delivery> Deliverys = response.Content.ReadAsAsync<IEnumerable<Delivery>>().Result;
                    ViewBag.eanToShow = productEan;
                    TempData["alertMessage"] = "The delivery was accepted sucessfully.";
                    return View("ViewDeliverys", Deliverys);
                }
                else
                {
                    TempData["alertMessage"] = "The delivery was not accepted - please try again later.";
                    Debug.WriteLine("Received a bad response from the web service.");
                }
            }
            catch
            {
                TempData["alertMessage"] = "Could not connect to re-stocker - please try again later";
                Debug.WriteLine("Error getting response from Restocker Service.");
            }
            ViewBag.eanToShow = productEan;
            return View("ViewDeliverys", null);
        }

        /// <summary>
        /// Choice for user to schedule a delivery or view deliveries in progress for a specific item (ean)
        /// </summary>
        public ActionResult RestockInfoButtonChoice(string productEAN, string restockAmount, string Restock, string ViewD)
        {
            var db = new Davison.Model.Context();
            List<Davison.Model.Product> products = db.Products.ToList();
            if (ViewD != null)
            { // Take user to view deliveries page
                ViewBag.eanToShow = productEAN;
                return View("ViewDeliverys");
            }
            else
            {
                if ((restockAmount != "") && (restockAmount != "0")) //ensure valid restock request
                {
                    var client = new HttpClient {BaseAddress = new System.Uri("http://localhost:42636/")};
                    client.DefaultRequestHeaders.Accept.ParseAdd("application/json");
                    client.Timeout = TimeSpan.FromMilliseconds(20000);
                    try
                    {
                        HttpResponseMessage response =
                            client.GetAsync("CreateDeliveryRequest?productEAN=" + productEAN + "&RestockAmount=" +
                                            restockAmount).Result;
                        // if successful display the data, otherwise log the bad response
                        if (response.IsSuccessStatusCode)
                        {
                            ViewBag.productEAN = new SelectList(products, "Ean", "Name");
                            ModelState.Clear(); // clears form fields
                            TempData["alertMessage"] = "The delivery request was successfully created.";
                            return View("RestockInfoView", products);
                        }
                        else
                        {
                            TempData["alertMessage"] =
                                "There has been a problem with the re-stocker please try again later.";
                            Debug.WriteLine("Received a bad response from the web service.");
                        }
                    }
                    catch
                    {
                        TempData["alertMessage"] =
                            "There has been a problem connecting to the re-stocker please try again later.";
                        Debug.WriteLine("Error getting response from Restocker Service.");
                    }
                }
                else
                {
                    ModelState.Clear(); // clears form fields
                    ViewBag.productEAN = new SelectList(products, "Ean", "Name");
                    TempData["alertMessage"] = "Please enter a valid quantity to re-stock";
                    return View("RestockInfoView", products);
                }
            }
            ModelState.Clear(); // clears form fields
            ViewBag.productEAN = new SelectList(products, "Ean", "Name");
            return View("RestockInfoView", products);
        }

        /// <summary>
        /// Returns the page showing a drop down list of all possible products for restocking purposes
        /// </summary>
        /// <returns>view showing restocking options</returns>
        public ActionResult RestockInfoView()
        {
            var db = new Davison.Model.Context();
            List<Davison.Model.Product> products = db.Products.ToList();
            ViewBag.productEAN = new SelectList(products, "Ean", "Name");
            return View(products);
        }

        /// <summary>
        /// Obtains page displaying products whos stock level is below their minimum stock threshold
        /// </summary>
        /// <returns>partial view showing products which exceed their specific minimum threshold</returns>
        public ActionResult ProductsExceedingThreshhold()
        {
            var client = new HttpClient { BaseAddress = new System.Uri("http://localhost:42636/") };
            client.DefaultRequestHeaders.Accept.ParseAdd("application/json");
            client.Timeout = TimeSpan.FromMilliseconds(20000);
            try
            {
                HttpResponseMessage response = client.GetAsync("GetProductsIfThreshholdHit").Result;
                // if successful display the data, otherwise log the bad response
                if (response.IsSuccessStatusCode)
                {
                    var Deliverys = response.Content.ReadAsAsync<IEnumerable<Davison.Model.Product>>().Result;
                    ViewBag.Threshholds = new int[50];
                    int counter = 0;
                    foreach (Davison.Model.Product p in Deliverys)
                    {

                        HttpResponseMessage response2 = client.GetAsync("GetThresholdForProduct?productEAN="+p.Ean).Result;
                        if (response2.IsSuccessStatusCode)
                        {
                           var thresh = response2.Content.ReadAsAsync<int>().Result;
                           ViewBag.Threshholds[counter]= thresh;
                            counter++;
                        }
                    }
                    return View("_HitRestockThreshViewPartial", Deliverys);
                }
                else
                    Debug.WriteLine("Received a bad response from the web service.");
            }
            catch (Exception ex) { Debug.WriteLine("Error getting response from Restocker Service: " + ex); }
            return View("_HitRestockThreshViewPartial", null);
        }

        /// <summary>
        /// Obtains a partial view of deliveries which have received for a particular product but awaiting acceptance
        /// </summary>
        /// <param name="ean">the ean of the product which has a delivery waiting</param>
        /// <returns></returns>
        public PartialViewResult DeliveriesAwaitingConfirm(string ean)
        {
            var client = new HttpClient { BaseAddress = new System.Uri("http://localhost:42636/") };
            client.DefaultRequestHeaders.Accept.ParseAdd("application/json");
            client.Timeout = TimeSpan.FromMilliseconds(20000);
            try
            {
                HttpResponseMessage response = client.GetAsync("GetDeliveriesForProduct?eanNumber=" + ean).Result;
                // if successful display the data, otherwise log the bad response
                if (response.IsSuccessStatusCode)
                {
                    var Deliverys = response.Content.ReadAsAsync<IEnumerable<Delivery>>().Result;
                    return PartialView("_DeliveriesPartial", Deliverys);
                }
                else
                    Debug.WriteLine("Received a bad response from the web service.");
            }
            catch
            {
                Debug.WriteLine("Error getting response from Restocker Service."); 
                
            }
            return PartialView("_DeliveriesPartial", null);
        }

        /// <summary>
        /// Obtains requested deliveries for a given ean
        /// </summary>
        /// <param name="ean">the products ean for which requested deliveries should be obtained for</param>
        /// <returns></returns>
        public PartialViewResult DeliveriesRequested(string ean)
        {

DavisonCorp/Views/Restocker/RestockInfoView.cshtml
@model List<Davison.Model.Product>
@{
    ViewBag.Title = "RestockInfoView";
    if (null != TempData["alertMessage"])
    {
        <script type="text/javascript">
       alert('@TempData["alertMessage"]');
        </script>
    }
}

<h2>Restocker Panel</h2>

@using (Html.BeginForm("RestockInfoButtonChoice", "Restocker"))
{
    @Html.DropDownList("productEAN")
    @*@Html.TextBox("RestockAmount");*@
    <p class="myInline">Restock Amount:</p> @Html.TextBox("RestockAmount", null, new { @class = "form-control mySelection" });
    <button type="submit" value="true" name="Restock">Schedule A Delivery</button>
    <button type="submit" value="true" name="ViewD">See Deliveries in progress</button>
}
<!--Show partial view for products exceeding threshold-->
@Html.Action("ProductsExceedingThreshhold", "Restocker")

DavisonCorp/Views/Restocker/ViewDeliverys.cshtml
@{
    ViewBag.Title = "ViewDeliverys";
    string ean = ViewBag.eanToShow;
}

@*<div class="fixedWidthButton">
    @Html.ActionLink("  Return to Re-stocker Panel", "RestockInfoView", "Restocker")
</div>*@

@using (Html.BeginForm("RestockInfoView", "Restocker"))
{
    <button type="submit" value="true" name="idNum" class="fixedWidthButton" style="margin-top:20px; width:200px;">Return to Re-stocker Panel</button>
}


<h2>Deliveries awaiting confirmation</h2>

@Html.Action("DeliveriesAwaitingConfirm", "Restocker", new { ean = ean })

<h2>Requested Deliverys</h2>

@Html.Action("DeliveriesRequested", "Restocker", new { ean = ean })

DavisonCorp/Views/Restocker/_DeliveriesPartial.cshtml
@model IEnumerable<DavisonCorpModel.Restocking.Delivery>

@{
    Layout = "";
    if (null != TempData["alertMessage"])
    {
        <script type="text/javascript">
       alert('@TempData["alertMessage"]');
        </script>
    }
}

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Quantity)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.ArrivalDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProductEan)
        </th>
    </tr>
    @{
        if (Model != null)
        {
            foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Quantity)
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.ArrivalDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ProductEan)
                    </td>
                    <td>
                        @Html.ActionLink("Accept Delivery", "AcceptDelivery", "Restocker", new { DeliveryId = item.Id, productEan = item.ProductEan, RestockAmount = item.Quantity }, null)
                    </td>
                </tr>
            }
        }
    }
</table>
@{
    if (Model == null)
    {

        <h2><font color="red">Cannot retrieve deliveries - Restocking is currently unavailable.</font></h2>
    }
}

DavisonCorp/Views/Restocker/_HitRestockThreshViewPartial.cshtml
@model List<Davison.Model.Product>

@{
    Layout = "";
    int[] thresh = ViewBag.Threshholds;
    int count = 0;
}

<h3>Products that have hit re-stocking threshhold</h3>

<table class="table">
    <tr>
        <th>
            Product
        </th>
        <th>
            Stock Level
        </th>
        <th>
            Last Restock
        </th>
        <th>
            Ean Number
        </th>
        <th>
            Restock Threshold
        </th>
    </tr>
    @{
        if (Model != null)
        {
            foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.StockLevel)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.LastRestock)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Ean)
                    </td>
                    <td>
                        @ViewBag.Threshholds[count].ToString()
                    </td>
                </tr>
                count = count + 1;
            }
        }
    }
</table>
@{
    if (Model == null)
    {
        <h2><font color="red">Restocking is currently unavailable, please try again later.</font></h2>
    }
}

DavisonCorp/Views/Restocker/_RequestsPartial.cshtml
@model IEnumerable<DavisonCorpModel.Restocking.Request>

@{
    Layout = "";
}

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Quantity)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.ExpectedDeliveryDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProductEan)
        </th>
    </tr>
    @{
        if (Model != null)
        {
            foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Quantity)
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.ExpectedDeliveryDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ProductEan)
                    </td>
                </tr>
            }
        }
    }
</table>

@{
    if (Model == null)
    {

        <h2><font color="red">Cannot retrive requested deliveries - Restocking is currently unavailable.</font></h2>
    }
}